name: 中青阅读2

on:
  workflow_dispatch:
  schedule:
     - cron: '0 */3 * * *'
jobs:
  build:
    runs-on: ubuntu-latest    
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/JONREAN2/js2.git ~/js
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/js
          npm install
          npm install cron
          npm install request
      - name: '运行 【中青阅读2】'
        run: |
          cd ~/js   
          node Task/Youth_AutoRead2.js
      - name: '运行 【中青看点2】'
        run: |
          cd ~/js   
          node Task/youthshare2.js
